### ISSUE TITLE
where is it?

### ISSUE THREAD

**Issue by ghost** [feren/feren-Themer-Source-Code#1]
hi, am surprised to find it empty.
joking aside if you need a theme tester on 16.04 contact me.

**Comment by dominichayesferen** [comment]
It's coming... as soon as I get Git configured and working... :/

PS: What do you think of this collab? https://github.com/Elbullazul/Longhorn-Collaboration

**Comment by dominichayesferen** [comment]
Yeah, sometime after I release 2016.1, I'll remember to upload it fully...

**Comment by ghost** [comment]
@feren thx.
as soon as there are files im testing them.

 b.t.w
its possible for me to generate a list of gtk3.18 and 3.20 classes.
Do you know a robust line per line replacing script? like mate porting
script but simpler.
 think it might be possible to apply all these changes to ambiance.

**Comment by dominichayesferen** [comment]
1. I'm actually not that sure, to be honest, I'm actually fairly new to GTK, just that I knew the answer to that question of yours on askubuntu because of Linux themes and knowledge of how it seems to behave
2. I only know how to do a working file replacement script in BASH, by MATE Porting, what exactly do you mean?
3. Just to get a better picture, which changes exactly to Ambiance?

**Comment by ghost** [comment]
mate porting script does have a ' as delimiter. you put all your
replace match pattern in it and the files to be replaced in src/ of
the folder script is in and run it.
very practical google for it.

what i need is something that reads a delimitered table by a semicolon
and exchanges match with replace. the number of pairs is very high and
it contains \* spaces and commas.

The outer css elements structure changed mostly they removed . and spaces .

**Comment by dominichayesferen** [comment]
it is coming... now.

**Comment by ghost** [comment]
ok. so its based on gambas. 

have a small incomplete 350 lines long comparision table between gtk3.18 and 3.20. once im finished publish it so one could patch a 3.18  theme. it'll will break here and there but more ll work than just using 3.18 one.
